# Local development database configuration
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Security configuration
cors.urls=${CORS_URLS:http://localhost:3000}
cors.enabled=${CORS_ENABLED:true}
csrf.enabled=${CSRF_ENABLED:false}
samesite.cookie.enabled=${SAMESITE_COOKIE_ENABLED:false}

# JWT configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

